# プロジェクトのメタ情報
[project]
name = "python-template"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

# 開発環境でのみ利用するパッケージ
[dependency-groups]
dev = [
    "pre-commit",
    "pytest",
    "ruff",
]

# pytest
[tool.pytest.ini_options]
pythonpath = ["src"]

# ruff
[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
